### Card application via kafka
POST http://localhost:8080/api/v1/cards/application
Content-Type: application/json
Accept-Language: pt-BR

{
  "cardholderName": "Jefferson Condotta234234234234234234234234234"
}

### Activate a blocked card
PATCH http://localhost:8080/api/v1/cards/5/activation
Content-Type: application/json

### Cancel any card
PATCH http://localhost:8080/api/v1/cards/3/cancellation
Content-Type: application/json

### Fetch a specific card
GET http://localhost:8080/api/v1/cards/122
Content-Type: application/json
Accept-Language: pt-BR

### Retrieve all cards in the db
GET http://localhost:8080/api/v1/cards
Content-Type: application/json