server:
  port: 8082

spring:
  application:
    name: card-management

  datasource:
    url: jdbc:mysql://localhost:23306/cards_db
    username: admin
    password: sB6mbtzNHmCQI4eN4yLo
    driverClassName: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  level:
    root: debug
    sql: info
    web: info

app:
  kafka:
    card-application-topic: card-application
    card-application-group-id: card-application
